name: manejapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  intl: ^0.18.1 
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/car1.png
    - assets/car2.png
    - assets/car3.png