name: manejapp
description: "ManejApp - Aplicación para clases de manejo"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  intl: ^0.20.2 
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  image_picker: ^1.1.2
  file_picker: ^8.1.6
  cached_network_image: ^3.4.1
  fl_chart: ^0.70.1
  animations: ^2.0.11
  provider: ^6.1.2
  shimmer: ^3.0.0
  table_calendar: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/car1.png
    - assets/car2.png
    - assets/car3.png